In [ ]:
import numpy as np
import pandas as pd
import difflib #difflib = if user gives spelling mistakes, it matchees with the closest match in the dataset
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
data = pd.read_csv('/content/movies.csv')


In [ ]:
data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [ ]:
data.shape

(4803, 24)

In [ ]:
data.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [ ]:
# prompt: return all the rows where atleast one column has a null value

null_rows = data[data.isnull().any(axis=1)]
print(null_rows)


      index     budget                                     genres  \
10       10  270000000   Adventure Fantasy Action Science Fiction   
15       15  225000000                   Adventure Family Fantasy   
24       24  207000000                     Adventure Drama Action   
27       27  209000000  Thriller Action Adventure Science Fiction   
33       33  210000000  Adventure Action Science Fiction Thriller   
...     ...        ...                                        ...   
4798   4798     220000                      Action Crime Thriller   
4799   4799       9000                             Comedy Romance   
4800   4800          0              Comedy Drama Romance TV Movie   
4801   4801          0                                        NaN   
4802   4802          0                                Documentary   

                                               homepage      id  \
10                              http://www.superman.com    1452   
15                                   

In [ ]:
selected_features = ['genres', 'keywords', 'original_language', 'overview', 'original_title', 'tagline', 'director']

In [ ]:
for feature in selected_features:
  data[feature] = data[feature].fillna(' ')

In [ ]:
combined_features = data['genres']+' '+data['keywords']+' '+data['original_language']+' '+data['overview']+' '+data['original_title']+' '+data['tagline']+' '+data['director']
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance   en A newlywed couple's honeym...
4800    Comedy Drama Romance TV Movie date love at fir...
4801        en When ambitious New York attorney Sam is...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [ ]:
vec = TfidfVectorizer()

In [ ]:
combined_vector = vec.fit_transform(combined_features)
print(combined_vector)

  (0, 3546)	0.1761585753531901
  (0, 12021)	0.12160040369007934
  (0, 15968)	0.03451268320924524
  (0, 25095)	0.0794824043040044
  (0, 7648)	0.15703851153348633
  (0, 1797)	0.2231830648617325
  (0, 4329)	0.18169396035018476
  (0, 906)	0.1346694708416423
  (0, 1087)	0.057825915958088815
  (0, 17810)	0.1832706421157659
  (0, 1121)	0.034981678055265586
  (0, 16170)	0.1774418030612134
  (0, 8827)	0.15243042128990827
  (0, 2510)	0.10967416859352877
  (0, 22952)	0.16582287340262125
  (0, 2285)	0.10782363202106786
  (0, 3415)	0.06812258518493207
  (0, 14815)	0.12008161160210211
  (0, 23771)	0.17050944000426274
  (0, 16066)	0.053595864524117166
  (0, 16514)	0.4081260020840575
  (0, 14999)	0.1666986428712021
  (0, 22853)	0.03400076250234548
  (0, 6590)	0.19790771532242676
  (0, 11902)	0.045789626148009174
  :	:
  (4802, 10096)	0.08633015245469466
  (4802, 24726)	0.08529765479055886
  (4802, 7891)	0.07778178784225029
  (4802, 16022)	0.06329136732496052
  (4802, 25234)	0.06485512803794394
  (4802

In [ ]:
similarity_score = cosine_similarity(combined_vector)
print(similarity_score)

[[1.         0.07009441 0.02614218 ... 0.0300072  0.01450035 0.00913983]
 [0.07009441 1.         0.05328068 ... 0.06699246 0.04631693 0.02105469]
 [0.02614218 0.05328068 1.         ... 0.02793522 0.03833481 0.01633207]
 ...
 [0.0300072  0.06699246 0.02793522 ... 1.         0.03550143 0.04140047]
 [0.01450035 0.04631693 0.03833481 ... 0.03550143 1.         0.03647806]
 [0.00913983 0.02105469 0.01633207 ... 0.04140047 0.03647806 1.        ]]


In [ ]:
print(similarity_score.shape)

(4803, 4803)


In [ ]:
Chosen_movie = input('Enter your favourite movie: ')

Enter your favourite movie: Spiderman


In [ ]:
corrected_list = difflib.get_close_matches(Chosen_movie, data['original_title'])
print(corrected_list)

['Spider-Man', 'Superman', 'Spider']


In [ ]:
corrected_movie = corrected_list[0]
print(corrected_movie)

Spider-Man


In [ ]:
index_of_movie = data[data.original_title == corrected_movie]['index'].values[0]
print(index_of_movie)

159


In [ ]:
similar_movies_score = list(enumerate(similarity_score[index_of_movie]))
print(similar_movies_score)

[(0, 0.016559779122080974), (1, 0.025896557691574743), (2, 0.023184894907023013), (3, 0.03205333832301362), (4, 0.007852268193251346), (5, 0.39487196643089206), (6, 0.017056683901795825), (7, 0.009312281302654714), (8, 0.01988602893267963), (9, 0.022572588219833788), (10, 0.018648109976987536), (11, 0.014484442018264487), (12, 0.029416853041509324), (13, 0.014132493970140821), (14, 0.054032773833006274), (15, 0.03653375639975991), (16, 0.0072798025519774205), (17, 0.01563377028066086), (18, 0.01079900265746286), (19, 0.030770888243664567), (20, 0.24088441261071492), (21, 0.010080634062177336), (22, 0.02059927438137605), (23, 0.013606927068901584), (24, 0.02620421875194462), (25, 0.00325854985306131), (26, 0.01585145440943725), (27, 0.026765907008432024), (28, 0.014474893114944725), (29, 0.031613008748831335), (30, 0.3003672630518481), (31, 0.03543260144502011), (32, 0.021972621781483796), (33, 0.0078049203169450534), (34, 0.012863605833317264), (35, 0.03563665641051262), (36, 0.0090620

In [ ]:
sorted_order = sorted(similar_movies_score, key = lambda x:x[1], reverse = True)
print(sorted_order)

[(159, 1.0000000000000002), (5, 0.39487196643089206), (1534, 0.33139858884191087), (30, 0.3003672630518481), (38, 0.2655981571616914), (20, 0.24088441261071492), (431, 0.18660940209428817), (1699, 0.1781457721097707), (3085, 0.11542921886952488), (3383, 0.10960901091077878), (37, 0.1083535249662532), (2163, 0.1021777962729034), (3129, 0.09875100941943914), (953, 0.09296083645249505), (2183, 0.09114455021324043), (2944, 0.08809800157196515), (1266, 0.08773791867993147), (3124, 0.0866870115409019), (2740, 0.08573013187156024), (1559, 0.0846053053575715), (1793, 0.08417889282785554), (1514, 0.08041959308630195), (1119, 0.07985560827096364), (2027, 0.07892757993173631), (1375, 0.07793504859861514), (3881, 0.07724921210882582), (135, 0.07676240436082399), (1098, 0.07260051985044728), (2218, 0.07255768153754447), (3846, 0.07192321154156278), (3575, 0.07166832271180396), (4024, 0.07141731264093534), (1598, 0.07068676227886006), (1239, 0.07052966126807707), (3073, 0.06948507923851859), (1816, 

In [ ]:
print('Suggested movies for you: ')
i=1
for movie in sorted_order:
  index = movie[0]
  title_from_index = data[data.index==index]['original_title'].values[0]
  if i<30:
    print(i,'.', title_from_index)
    i=i+1

Suggested movies for you: 
1 . Spider-Man
2 . Spider-Man 3
3 . Arachnophobia
4 . Spider-Man 2
5 . The Amazing Spider-Man 2
6 . The Amazing Spider-Man
7 . Charlotte's Web
8 . Along Came a Spider
9 . Spider
10 . Losin' It
11 . Oz: The Great and Powerful
12 . The Covenant
13 . Jungle Shuffle
14 . Gremlins 2: The New Batch
15 . Home for the Holidays
16 . Army of Darkness
17 . Cirque du Freak: The Vampire's Assistant
18 . The Reef
19 . The New Guy
20 . The Notebook
21 . In Good Company
22 . The Quick and the Dead
23 . 21 Jump Street
24 . I Am Sam
25 . Sky High
26 . Beginners
27 . The Wolfman
28 . Love in the Time of Cholera
29 . Death Sentence
